name: checks

on:
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.svelte"
      - "**/*.md"
      - "tests/**"
      - "configs/**"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      # Prevent Husky/prepare from running in CI
      HUSKY: '0'
      # Optional: faster installs, keeps cache clean
      PNPM_CACHE_DIR: ~/.pnpm-store
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # Corepack ships with Node 20 — this makes pnpm available on PATH
      - name: Enable Corepack and pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.15.9 --activate
          pnpm --version

      - name: Verify pnpm on PATH
        run: |
          which pnpm || echo "pnpm missing"
          node -v
          pnpm -v

      # Optional: restore a separate pnpm store cache
      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: pnpm-store-

      - name: Install (frozen lockfile, ignore scripts in CI)
        run: pnpm -w install --frozen-lockfile --ignore-scripts

      # Guard against legacy pnpm-setup references
      - name: Assert no legacy pnpm-setup usage
        run: |
          if git grep -n "./.github/actions/pnpm-setup" -- ':!**/node_modules/**' 2>/dev/null; then
            echo "Legacy pnpm-setup still referenced"; exit 1; 
          fi

      # tests
      - run: pnpm run test:all

      # style gates
      - run: pnpm -w lint
      - run: pnpm run format:check

      # docs gates (you already have these)
      - run: pnpm run docs:lint
      - run: pnpm run docs:links