name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# prevent concurrent runs on the same ref (keeps previews/builds tidy)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

env:
  # keep build sizes lean; skip source maps in CI builds unless you need them
  VITE_SOURCEMAP: false
  # fail PRs if Lighthouse a11y < 95
  LIGHTHOUSE_MIN_A11Y: '0.95'

jobs:
  install:
    name: Install (frozen lockfile)
    runs-on: ubuntu-latest
    env:
      # Prevent Husky/prepare from running in CI
      HUSKY: '0'
      # Optional: faster installs, keeps cache clean
      PNPM_CACHE_DIR: ~/.pnpm-store
    
    # Force bash everywhere so scripts behave consistently
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20) with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable pnpm via Corepack (matches packageManager)
        run: |
          set -euo pipefail
          node -v
          corepack --version
          corepack enable
          corepack prepare pnpm@9.15.9 --activate

      - name: Verify pnpm works & where it lives
        run: |
          set -euo pipefail
          echo "PATH=$PATH"
          command -v pnpm
          type -a pnpm
          pnpm --version
          pnpm config get store-dir || true

      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install deps (frozen lockfile, ignore scripts in CI)
        run: pnpm -w install --frozen-lockfile --ignore-scripts

  lint-type:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    needs: install
    env:
      # Prevent Husky/prepare from running in CI
      HUSKY: '0'
      # Optional: faster installs, keeps cache clean
      PNPM_CACHE_DIR: ~/.pnpm-store
    
    # Force bash everywhere so scripts behave consistently
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20) with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable pnpm via Corepack (matches packageManager)
        run: |
          set -euo pipefail
          node -v
          corepack --version
          corepack enable
          corepack prepare pnpm@9.15.9 --activate

      - name: Verify pnpm works & where it lives
        run: |
          set -euo pipefail
          echo "PATH=$PATH"
          command -v pnpm
          type -a pnpm
          pnpm --version
          pnpm config get store-dir || true

      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Restore node_modules from install job
        run: pnpm -w install --frozen-lockfile --ignore-scripts

      - name: ESLint
        run: pnpm -w run lint --if-present

      - name: Prettier (check)
        run: pnpm -w run format:check --if-present

      - name: TypeScript check
        run: pnpm -w run typecheck --if-present

      - name: Docs lint (markdownlint) - optional
        run: pnpm -w run docs:lint --if-present

  unit-tests:
    name: Unit/Integration Tests
    runs-on: ubuntu-latest
    needs: install
    env:
      # Optional: faster installs, keeps cache clean
      PNPM_CACHE_DIR: ~/.pnpm-store
    
    # Force bash everywhere so scripts behave consistently
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20) with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable pnpm via Corepack (matches packageManager)
        run: |
          set -euo pipefail
          node -v
          corepack --version
          corepack enable
          corepack prepare pnpm@9.15.9 --activate

      - name: Verify pnpm works & where it lives
        run: |
          set -euo pipefail
          echo "PATH=$PATH"
          command -v pnpm
          type -a pnpm
          pnpm --version
          pnpm config get store-dir || true

      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Restore node_modules from install job
        run: pnpm -w install --frozen-lockfile --ignore-scripts
        env:
          HUSKY: 0

      - name: Run tests (Node.js + Vitest)
        run: pnpm -w run test:all --if-present
        env:
          CI: true
          HUSKY: 1  # Enable Husky for test-precommit-e2e

  build:
    name: Build (web)
    runs-on: ubuntu-latest
    needs: [lint-type, unit-tests]
    env:
      # Prevent Husky/prepare from running in CI
      HUSKY: '0'
      # Optional: faster installs, keeps cache clean
      PNPM_CACHE_DIR: ~/.pnpm-store
    
    # Force bash everywhere so scripts behave consistently
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20) with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable pnpm via Corepack (matches packageManager)
        run: |
          set -euo pipefail
          node -v
          corepack --version
          corepack enable
          corepack prepare pnpm@9.15.9 --activate

      - name: Verify pnpm works & where it lives
        run: |
          set -euo pipefail
          echo "PATH=$PATH"
          command -v pnpm
          type -a pnpm
          pnpm --version
          pnpm config get store-dir || true

      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Restore node_modules from install job
        run: pnpm -w install --frozen-lockfile --ignore-scripts

      # Build TypeScript packages first
      - name: Build TypeScript packages
        run: pnpm -w run build --if-present

      # If your web app package name differs, adjust filter
      - name: Build SvelteKit (adapter-static)
        run: pnpm --filter @draconia/web build --if-present

      - name: Upload static site artifact for GH Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/build

  lighthouse:
    name: Lighthouse (a11y gate)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Start static server
        run: |
          npx http-server ./ -p 4173 -s &> /dev/null &
          echo $! > server.pid
        working-directory: ./ # artifact root

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: 'http://localhost:4173'
          configPath: |
            {
              "ci": {
                "assert": {
                  "assertions": {
                    "categories:accessibility": ["error", {"minScore": ${{ env.LIGHTHOUSE_MIN_A11Y }}}],
                    "categories:performance": ["warn", {"minScore": 0.90}]
                  }
                }
              }
            }
          uploadArtifacts: true
          runs: 1

      - name: Stop server
        if: always()
        run: kill $(cat server.pid) || true

  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, lighthouse]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4