name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# prevent concurrent runs on the same ref (keeps previews/builds tidy)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

env:
  # keep build sizes lean; skip source maps in CI builds unless you need them
  VITE_SOURCEMAP: false
  # fail PRs if Lighthouse a11y < 95
  LIGHTHOUSE_MIN_A11Y: '0.95'

jobs:
  lint-type-test:
    name: Lint, Type & Test
    runs-on: ubuntu-latest
    env:
      HUSKY: '0'
      PNPM_CACHE_DIR: ~/.pnpm-store
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
          run_install: false

      - name: Install and Link workspace dependencies
        env:
          HUSKY: '0'
        run: |
          echo "Installing and linking workspace dependencies..."
          pnpm -w install
          echo "Explicitly linking workspace packages..."
          cd packages/logger && pnpm link @draconia/db || echo "Link failed"
          cd ../db && pnpm link || echo "Link failed"
          echo "Verifying workspace links:"
          ls -la packages/logger/node_modules/@draconia/ || echo "No @draconia links found"
          echo "Testing @draconia/db resolution:"
          node -e "console.log('@draconia/db available:', require.resolve('@draconia/db'))" || echo "@draconia/db not resolvable"
          echo "Creating symlink manually if needed:"
          mkdir -p packages/logger/node_modules/@draconia
          ln -sf ../../../db packages/logger/node_modules/@draconia/db || echo "Symlink failed"
          echo "Final verification:"
          ls -la packages/logger/node_modules/@draconia/ || echo "No @draconia links found"

      - name: Build (TS project references)
        run: |
          pnpm -w run clean
          pnpm -w run build:ci

      - name: Tests
        run: pnpm -w run test:all

      - name: ESLint
        run: pnpm -w run lint

      - name: Prettier (check)
        run: pnpm -w run format:check

      - name: TypeScript check
        run: pnpm -w run typecheck

      - name: Docs lint (markdownlint) - optional
        run: pnpm -w run docs:lint

      - name: Size budgets (gate)
        env:
          BUDGET_BASE_KB: 200
          BUDGET_LOGGER_KB: 8
        run: pnpm run size:check

  build-web:
    name: Build (web)
    runs-on: ubuntu-latest
    needs: [lint-type-test]
    env:
      HUSKY: '0'
      PNPM_CACHE_DIR: ~/.pnpm-store
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
          run_install: false

      - name: Install
        env:
          HUSKY: '0'
        run: pnpm -w install --frozen-lockfile

      - name: Build (TS project references)
        run: |
          pnpm -w run clean
          pnpm -w run build:ci

      # Build SvelteKit app using the built packages
      - name: Build SvelteKit (adapter-static)
        env:
          BASE_PATH: /${{ github.event.repository.name }}
        run: pnpm --filter @draconia/web build --if-present

      - name: Upload dist artifact (for previews/tests)
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/build/**/*

      - name: Upload static site artifact for GH Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/build

  lighthouse:
    name: Lighthouse (a11y gate)
    runs-on: ubuntu-latest
    needs: build-web
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Start static server
        run: |
          npx http-server ./ -p 4173 -s &> /dev/null &
          echo $! > server.pid
        working-directory: ./ # artifact root

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: 'http://localhost:4173'
          configPath: |
            {
              "ci": {
                "assert": {
                  "assertions": {
                    "categories:accessibility": ["error", {"minScore": ${{ env.LIGHTHOUSE_MIN_A11Y }}}],
                    "categories:performance": ["warn", {"minScore": 0.90}]
                  }
                }
              }
            }
          uploadArtifacts: true
          runs: 1

      - name: Stop server
        if: always()
        run: kill $(cat server.pid) || true

  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-web, lighthouse]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4