name: docs
on:
  pull_request:
    paths:
      - "**/*.md"
      - "docs/**"
      - "packages/**"
      - "apps/**"
      - "tests/**"
      - ".github/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      # Prevent Husky/prepare from running in CI
      HUSKY: '0'
      # Optional: faster installs, keeps cache clean
      PNPM_CACHE_DIR: ~/.pnpm-store
    
    # Force bash everywhere so scripts behave consistently
    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout (fetch all history + base ref)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # unshallow so we can diff properly

      # Optional but fast: fetch the PR base explicitly (helps forks)
      - name: Fetch base branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

      # Actionlint via Reviewdog (keeps nice PR annotations)
      - name: Actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
          fail_level: error         # <- replace fail_on_error

      - name: Setup Node (20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable pnpm via Corepack (matches packageManager)
        run: |
          set -euo pipefail
          node -v
          corepack --version
          corepack enable
          corepack prepare pnpm@9.15.9 --activate

      - name: Verify pnpm works & where it lives
        run: |
          set -euo pipefail
          echo "PATH=$PATH"
          command -v pnpm
          type -a pnpm
          pnpm --version
          pnpm config get store-dir || true

      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install (frozen lockfile, ignore scripts in CI)
        run: pnpm -w install --ignore-scripts
      - run: pnpm run docs:lint
      - run: pnpm run docs:links

      - name: Require docs change
        run: node .github/scripts/require-docs-change.mjs
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}            # PR base (e.g., main)
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha || '' }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha || '' }}