name: docs
on:
  pull_request:
    paths: ["**/*.md", "packages/**", "apps/**", "tests/**", ".github/**", "docs/**"]

permissions:
  contents: read
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: nofilter
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm i
      - run: pnpm run docs:lint
      - run: pnpm run docs:links
      - name: Enforce docs presence on code/test changes
        run: node .github/scripts/require-docs-change.mjs