name: docs
on:
  pull_request:
    paths:
      - "**/*.md"
      - "docs/**"
      - "packages/**"
      - "apps/**"
      - "tests/**"
      - ".github/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (fetch all history + base ref)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # unshallow so we can diff properly

      # Optional but fast: fetch the PR base explicitly (helps forks)
      - name: Fetch base branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

      # Actionlint via Reviewdog (keeps nice PR annotations)
      - name: Actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
          fail_level: error         # <- replace fail_on_error

      # Set up pnpm — DO NOT set "version" here when you have packageManager in package.json
      - uses: pnpm/action-setup@v4
        with:
          run_install: false        # we'll install after Node is set up

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm -v                # debug: should print 9.x from package.json
      - run: pnpm install --frozen-lockfile
      - run: pnpm run docs:lint
      - run: pnpm run docs:links

      - name: Require docs change
        run: node .github/scripts/require-docs-change.mjs
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}            # PR base (e.g., main)
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha || '' }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha || '' }}