name: E2E Smoke (Playwright)

on:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
          run_install: false

      - name: Install deps
        env:
          HUSKY: '0'
        run: |
          echo "=== DEBUGGING WORKSPACE LINKING ==="
          echo "Current working directory: $(pwd)"
          echo "Checking workspace config:"
          cat pnpm-workspace.yaml
          echo "Installing with workspace recreation:"
          rm -rf node_modules apps/*/node_modules packages/*/node_modules || true
          pnpm -w install --shamefully-hoist=false --link-workspace-packages=true
          echo "=== CHECKING WORKSPACE LINKS ==="
          ls -la apps/web/node_modules/@draconia/ || echo "No @draconia links in web app"
          echo "=== TESTING MODULE RESOLUTION ==="
          cd apps/web && node -e "console.log('@draconia/logger:', require.resolve('@draconia/logger'))" || echo "@draconia/logger not resolvable from web app"

      - name: Build workspace dependencies
        run: pnpm -w run build:ci

      - name: Copy workspace packages for Vite resolution (GitHub Actions workaround)
        run: |
          echo "=== COPYING WORKSPACE PACKAGES ==="
          # Create @draconia namespace directory in web app
          mkdir -p apps/web/node_modules/@draconia
          
          # Copy built packages to where Vite expects them
          echo "Copying @draconia/shared..."
          cp -r packages/shared apps/web/node_modules/@draconia/shared
          
          echo "Copying @draconia/db..."
          cp -r packages/db apps/web/node_modules/@draconia/db
          
          echo "Copying @draconia/logger..."
          cp -r packages/logger apps/web/node_modules/@draconia/logger
          
          echo "=== VERIFYING COPIED PACKAGES ==="
          ls -la apps/web/node_modules/@draconia/
          echo "Testing @draconia/logger resolution:"
          cd apps/web && node -e "console.log('@draconia/logger resolved to:', require.resolve('@draconia/logger'))"

      - name: Build (Pages base path)
        env:
          BASE_PATH: /${{ github.event.repository.name }}
        run: pnpm --filter @draconia/web build

      - name: Install Playwright browsers (cached)
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json','**/pnpm-lock.yaml') }}

      - run: npx playwright install --with-deps

      - name: Start preview server
        run: pnpm --filter @draconia/web preview &

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:4173/${{ github.event.repository.name }}/

      - name: Run smoke tests (Chromium only)
        env:
          BASE_URL: http://127.0.0.1:4173/${{ github.event.repository.name }}
        run: npx playwright test --project=chromium --reporter=line

      - name: Upload Playwright report (on fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
