name: E2E Smoke (Playwright)

on:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
          run_install: false

      - name: Install deps
        env:
          HUSKY: '0'
        run: |
          echo "Installing workspace dependencies with hoisted structure..."
          pnpm -w install --config.node-linker=hoisted

      - name: Build workspace dependencies
        run: pnpm -w run build:ci

      - name: Copy workspace packages for Vite resolution (GitHub Actions workaround)
        run: |
          mkdir -p apps/web/node_modules/@draconia
          cp -r packages/shared apps/web/node_modules/@draconia/shared
          cp -r packages/db apps/web/node_modules/@draconia/db
          cp -r packages/logger apps/web/node_modules/@draconia/logger

      - name: Verify hoisted structure for E2E
        run: |
          echo "=== Verifying hoisted structure for E2E ==="
          ls -la node_modules/pixi.js/ 2>/dev/null && echo "✅ pixi.js is hoisted!" || echo "❌ pixi.js not hoisted"

      - name: Build (Pages base path)
        env:
          BASE_PATH: /${{ github.event.repository.name }}
        run: pnpm --filter @draconia/web build

      - name: Install Playwright browsers (cached)
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json','**/pnpm-lock.yaml') }}

      - run: npx playwright install --with-deps

      - name: Start preview server
        run: pnpm --filter @draconia/web preview &

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:4173/${{ github.event.repository.name }}/

      - name: Debug: List files and check config
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Listing tests directory ==="
          ls -la tests/
          echo "=== Listing e2e directory ==="
          ls -la tests/e2e/
          echo "=== Checking Playwright config ==="
          cat configs/playwright.config.ts
          echo "=== Testing Playwright list ==="
          npx playwright test --config=configs/playwright.config.ts --list

      - name: Run smoke tests (Chromium only)
        env:
          BASE_URL: http://127.0.0.1:4173/${{ github.event.repository.name }}
        run: npx playwright test --config=configs/playwright.config.ts --project=chromium --reporter=line

      - name: Upload Playwright report (on fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
